//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING()
        {
            this.EMPLOYEEDATETIMESLOTs = new HashSet<EMPLOYEEDATETIMESLOT>();
        }
    
        public int BOOKINGID { get; set; }
        public Nullable<int> PROPERTYID { get; set; }
        public int USERID { get; set; }
        public int CLIENTID { get; set; }
    
        public virtual PROPERTY PROPERTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEEDATETIMESLOT> EMPLOYEEDATETIMESLOTs { get; set; }
    }
}
