//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public int DOCUMENTID { get; set; }
        public int RENTALAPPLICATIONID { get; set; }
        public string IDENTITYDOCUMENT { get; set; }
        public string PAYSLIP { get; set; }
        public string BURSARYLETTER { get; set; }
    
        public virtual RENTALAPPLICATION RENTALAPPLICATION { get; set; }
    }
}
