//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEESLOTSTATU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEESLOTSTATU()
        {
            this.EMPLOYEEDATETIMESLOTs = new HashSet<EMPLOYEEDATETIMESLOT>();
        }
    
        public int EMPLOYEESLOTSTAUSID { get; set; }
        public string EMPLOYEESLOTSTATUSDESCR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEEDATETIMESLOT> EMPLOYEEDATETIMESLOTs { get; set; }
    }
}
