//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPERTY()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.PROPERTYPHOTOes = new HashSet<PROPERTYPHOTO>();
            this.RENTAL_AGREEMENT = new HashSet<RENTAL_AGREEMENT>();
            this.RENTALAMOUNTs = new HashSet<RENTALAMOUNT>();
            this.RENTALAPPLICATIONs = new HashSet<RENTALAPPLICATION>();
        }
    
        public int PROPERTYID { get; set; }
        public Nullable<int> PROPERTYSTATUSID { get; set; }
        public Nullable<int> PROPERTYTYPEID { get; set; }
        public Nullable<int> AGENT_ID { get; set; }
        public Nullable<int> AREAID { get; set; }
        public string PROPERTYDESCRIPTION { get; set; }
        public string ADDRESS { get; set; }
        public string SIZE { get; set; }
        public Nullable<int> NUMBED { get; set; }
        public Nullable<int> NUMBBATH { get; set; }
        public string GARDEN { get; set; }
        public string ADDITIONALINFO { get; set; }
        public Nullable<System.DateTime> LISTINGDATE { get; set; }
        public Nullable<System.DateTime> AVAILABLEDATE { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual AREA AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        public virtual PROPERTYSTATU PROPERTYSTATU { get; set; }
        public virtual PROPERTYTYPE PROPERTYTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYPHOTO> PROPERTYPHOTOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL_AGREEMENT> RENTAL_AGREEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTALAMOUNT> RENTALAMOUNTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTALAPPLICATION> RENTALAPPLICATIONs { get; set; }
    }
}
