//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASELINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PURCHASELINE()
        {
            this.JOBTASKs = new HashSet<JOBTASK>();
        }
    
        public int PURCHASELINEID { get; set; }
        public int ITEMID { get; set; }
        public int PURCHASEID { get; set; }
        public Nullable<int> JOBTASKID { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBTASK> JOBTASKs { get; set; }
        public virtual JOBTASK JOBTASK { get; set; }
        public virtual PURCHASE PURCHASE { get; set; }
    }
}
