//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTAL_AGREEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENTAL_AGREEMENT()
        {
            this.COMPLAINTs = new HashSet<COMPLAINT>();
            this.INSPECTIONs = new HashSet<INSPECTION>();
            this.JOBs = new HashSet<JOB>();
            this.PAYMENTs = new HashSet<PAYMENT>();
            this.RENTALAPPLICATIONs = new HashSet<RENTALAPPLICATION>();
            this.TERMINATEDAGREEMENTs = new HashSet<TERMINATEDAGREEMENT>();
        }
    
        public int RENTALAGREEMENTID { get; set; }
        public int RENTALSTATUSID { get; set; }
        public int CLIENTID { get; set; }
        public Nullable<int> RENTALAPPLICATIONID { get; set; }
        public int PROPERTYID { get; set; }
        public Nullable<System.DateTime> RENTALSTARTDATE { get; set; }
        public Nullable<System.DateTime> RENTALENDDATE { get; set; }
        public Nullable<int> AMOUNTDUE { get; set; }
        public Nullable<System.DateTime> DepositDueDate { get; set; }
        public string REFERENCE_NO { get; set; }
        public Nullable<System.DateTime> ExtendRentalDate { get; set; }
        public Nullable<System.DateTime> TerminateRentalDate { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPLAINT> COMPLAINTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTION> INSPECTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual RENTAL_STATUS RENTAL_STATUS { get; set; }
        public virtual RENTALAPPLICATION RENTALAPPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTALAPPLICATION> RENTALAPPLICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TERMINATEDAGREEMENT> TERMINATEDAGREEMENTs { get; set; }
    }
}
