//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_test_audit_trail
    {
        public int id { get; set; }
        public System.DateTime audit_datetime_utc { get; set; }
        public string audit_type { get; set; }
        public string audit_user { get; set; }
        public string table_name { get; set; }
        public string key_values { get; set; }
        public string old_values { get; set; }
        public string new_values { get; set; }
        public string changed_columns { get; set; }
    }
}
