//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.RENTAL_AGREEMENT = new HashSet<RENTAL_AGREEMENT>();
            this.RENTALAPPLICATIONs = new HashSet<RENTALAPPLICATION>();
        }
    
        public int CLIENTID { get; set; }
        public int USERID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string PHONENUMBER { get; set; }
        public string EMAIL { get; set; }
        public string PASSPORT_NO { get; set; }
        public string ID { get; set; }
        public string NATIONALITY { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<bool> ISSTUDENT { get; set; }
        public string RESIDENTIAL_ADDRESS { get; set; }
        public string POSTAL_ADDRESS { get; set; }
        public string NAME_OF_EMPLOYER { get; set; }
        public string OCCUPATION { get; set; }
        public string WORK_ADDRESS { get; set; }
        public string WORK_TEL__NO { get; set; }
        public Nullable<decimal> GROSS_SALARY { get; set; }
        public string OTP { get; set; }
        public Nullable<bool> verified { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL_AGREEMENT> RENTAL_AGREEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTALAPPLICATION> RENTALAPPLICATIONs { get; set; }
    }
}
