//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATETIMESLOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATETIMESLOT()
        {
            this.EMPLOYEEDATETIMESLOTs = new HashSet<EMPLOYEEDATETIMESLOT>();
        }
    
        public int DATETIMESLOTID { get; set; }
        public int DATEID { get; set; }
        public Nullable<int> AREAID { get; set; }
        public int SLOTID { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual DATE DATE { get; set; }
        public virtual SLOT SLOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEEDATETIMESLOT> EMPLOYEEDATETIMESLOTs { get; set; }
    }
}
