//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.COMPLAINTs = new HashSet<COMPLAINT>();
            this.EMPLOYEEDATETIMESLOTs = new HashSet<EMPLOYEEDATETIMESLOT>();
            this.INSPECTIONs = new HashSet<INSPECTION>();
            this.JOBs = new HashSet<JOB>();
        }
    
        public int EMPLOYEEID { get; set; }
        public int USERID { get; set; }
        public int EMPLOYEETYPEID { get; set; }
        public string EMPLOYEENATIONALID { get; set; }
        public Nullable<int> EMPLOYEEPASSPORTNO { get; set; }
        public Nullable<System.DateTime> DATEEMPLOYED { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string DATEOFBIRTH { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPLAINT> COMPLAINTs { get; set; }
        public virtual EMPLOYEETYPE EMPLOYEETYPE { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEEDATETIMESLOT> EMPLOYEEDATETIMESLOTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTION> INSPECTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOBs { get; set; }
    }
}
