//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOB()
        {
            this.FEEDBACKs = new HashSet<FEEDBACK>();
            this.JOBTASKs = new HashSet<JOBTASK>();
        }
    
        public int JOBID { get; set; }
        public int RENTALAGREEMENTID { get; set; }
        public int JOBTYPEID { get; set; }
        public Nullable<int> FEEDBACKID { get; set; }
        public int JOBSTATUSID { get; set; }
        public Nullable<System.DateTime> DATEREQUESTED { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<System.DateTime> DATECOMPLETED { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEEDBACK> FEEDBACKs { get; set; }
        public virtual FEEDBACK FEEDBACK { get; set; }
        public virtual JOBSTATU JOBSTATU { get; set; }
        public virtual JOBTYPE JOBTYPE { get; set; }
        public virtual RENTAL_AGREEMENT RENTAL_AGREEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBTASK> JOBTASKs { get; set; }
    }
}
