//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTALAPPLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENTALAPPLICATION()
        {
            this.DOCUMENTs = new HashSet<DOCUMENT>();
            this.RENTAL_AGREEMENT = new HashSet<RENTAL_AGREEMENT>();
        }
    
        public int RENTALAPPLICATIONID { get; set; }
        public int PROPERTYID { get; set; }
        public int CLIENTID { get; set; }
        public Nullable<int> RENTALAGREEMENTID { get; set; }
        public Nullable<int> RENTALAPPLICATIONSTATUSID { get; set; }
        public Nullable<System.DateTime> APPLICATIONDATE { get; set; }
        public Nullable<System.DateTime> PREFERREDSTARTDATE { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENT> DOCUMENTs { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL_AGREEMENT> RENTAL_AGREEMENT { get; set; }
        public virtual RENTAL_AGREEMENT RENTAL_AGREEMENT1 { get; set; }
        public virtual RENTALAPPLICATIONSTATU RENTALAPPLICATIONSTATU { get; set; }
    }
}
