//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CLIENTs = new HashSet<CLIENT>();
            this.DEACTIVATEDUSERs = new HashSet<DEACTIVATEDUSER>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public int USERID { get; set; }
        public Nullable<int> USERTYPEID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string RESETOTP { get; set; }
        public Nullable<bool> UserPasswordChangeRequest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT> CLIENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEACTIVATEDUSER> DEACTIVATEDUSERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual USERTYPE USERTYPE { get; set; }
    }
}
