export class Inspection {
INSPECTIONID:string;
INSPECTION_STATUS_ID: number;
INSPECTIONTYPEID :number;
RENTALAGREEMENTID :number;
INSPECTIONDATETIME:	Date;	
INSPECTIONNOTE:string;
  static INSPECTIONID: any;
	
}
